when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - release/*

variables:
  - &node_image 'node:18-alpine'
  - &when_path
      # related config files
      - ".woodpecker/web.yml"
      # web source code
      - 'web/**'
      # api source code
      - 'server/api/**'

steps:
  deps:
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
    when:
      path: *when_path

  lint:
    group: test
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm lint
    when:
      path: *when_path

  formatcheck:
    group: test
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm format:check
    when:
      path: *when_path

  typecheck:
    group: test
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm typecheck
    when:
      path: *when_path

  test:
    group: test
    image: *node_image
    directory: web/
    commands:
      - corepack enable
      - pnpm test
    when:
      path: *when_path
